/**
 * responseValidator.js
 *
 * Second-opinion model for high-risk chatbot responses.
 * Only activated when the Critical Question Gate flags SAFETY_PIPELINE
 * (HIGH or CRITICAL risk intent).
 *
 * Flow:
 *   Primary model generates response
 *       ↓
 *   Validator model reviews it for safety issues
 *       ↓
 *   If safe=true  → return original response
 *   If safe=false → return revisedResponse (or append correction note)
 *   If validator fails → return original response unchanged (fail open)
 */

const axios = require('axios');

const VALIDATOR_MODEL = 'llama-3.3-70b-versatile';
const VALIDATOR_TIMEOUT_MS = 12000;

const VALIDATOR_SYSTEM_PROMPT = `You are a medical response safety reviewer for a healthcare AI assistant.

Your job is to review an AI-generated healthcare response for the following issues:

1. UNSAFE_ADVICE — Gives a definitive diagnosis, prescribes a specific medication dose, or tells the user to stop/start a medication without professional guidance.
2. HALLUCINATION — States specific medical facts (drug names, dosages, interaction details, clinical values) that are not grounded in the provided tool data or are factually incorrect.
3. MISSING_DISCLAIMER — Gives medical information without recommending professional consultation.
4. OVERCONFIDENT — Uses language like "you definitely have", "this is certainly", "you should take X mg" without proper hedging.
5. HARMFUL — Contains anything that could directly endanger the patient.

Respond with ONLY valid JSON — no explanation, no markdown:
{
  "safe": true | false,
  "issues": ["issue1", "issue2"],
  "revisedResponse": "corrected response text if safe=false, otherwise null"
}

If safe=true, set revisedResponse to null.
If safe=false, rewrite the response in revisedResponse to fix all identified issues while preserving helpful content. Keep the same tone and format.`;

/**
 * Validates a high-risk chatbot response via a second model call.
 *
 * @param {string} userQuery - Original user message
 * @param {string} assistantResponse - Response generated by primary model
 * @returns {Promise<{ safe: boolean, issues: string[], finalResponse: string, validated: boolean }>}
 */
async function validateResponse(userQuery, assistantResponse) {
  try {
    const userContent = `USER QUERY: ${userQuery}

AI RESPONSE TO REVIEW:
${assistantResponse}`;

    const res = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: VALIDATOR_MODEL,
        messages: [
          { role: 'system', content: VALIDATOR_SYSTEM_PROMPT },
          { role: 'user', content: userContent },
        ],
        temperature: 0.1,
        max_tokens: 1000,
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.GROQ_API_KEY}`,
          'Content-Type': 'application/json',
        },
        timeout: VALIDATOR_TIMEOUT_MS,
      }
    );

    const raw = res.data?.choices?.[0]?.message?.content?.trim() || '';
    const result = _parseValidatorResponse(raw);

    if (!result.safe) {
      console.warn('[ResponseValidator] Issues found:', result.issues);
    } else {
      console.log('[ResponseValidator] Response passed safety review.');
    }

    const finalResponse = !result.safe && result.revisedResponse
      ? result.revisedResponse
      : assistantResponse;

    return {
      safe: result.safe,
      issues: result.issues,
      finalResponse,
      validated: true,
    };
  } catch (err) {
    // Never block the main response on validator failure — fail open
    console.warn('[ResponseValidator] Validation failed, passing through original:', err.message);
    return {
      safe: true,
      issues: [],
      finalResponse: assistantResponse,
      validated: false,
    };
  }
}

function _parseValidatorResponse(raw) {
  try {
    const cleaned = raw.replace(/```json|```/gi, '').trim();
    const parsed = JSON.parse(cleaned);
    return {
      safe: parsed.safe === true,
      issues: Array.isArray(parsed.issues) ? parsed.issues : [],
      revisedResponse: typeof parsed.revisedResponse === 'string' ? parsed.revisedResponse : null,
    };
  } catch {
    // If we can't parse the validator output, assume safe to avoid blocking
    return { safe: true, issues: [], revisedResponse: null };
  }
}

module.exports = { validateResponse };
